services:
  ansible-control:
    hostname: ansible-control
    container_name: ansible-control
    image: ansible-control:latest
    ports:
     - 22:22
     - 7681:7681
    privileged: true
    volumes:
      - ${PWD}/config/ansible-control:/etc/ansible
      - ${PWD}/playbook:/playbook
    networks:
     - bridgenetwork
  clickhouse-01:
    hostname: clickhouse-01
    container_name: clickhouse-01
    image: managed-nodes-base:latest
    ports:
     - 2222:22
     - 8123:8123
     - 9000:9000
    volumes:
     - ${PWD}/data/fs/clickhouse-01:/var/lib/clickhouse
    networks:
     - bridgenetwork
  clickhouse-02:
    hostname: clickhouse-02
    container_name: clickhouse-02
    image: managed-nodes-base:latest
    ports:
     - 2223:22
     - 8124:8124
     - 9001:9001
    volumes:
     - ${PWD}/data/fs/clickhouse-02:/var/lib/clickhouse
    networks:
     - bridgenetwork
  keeper-01:
    hostname: keeper-01
    container_name: keeper-01
    image: managed-nodes-base:latest
    ports:
     - 2224:22
    volumes:
     - ${PWD}/data/fs/keeper-01:/var/lib/clickhouse
    networks:
     - bridgenetwork
  keeper-02:
    hostname: keeper-02
    container_name: keeper-02
    image: managed-nodes-base:latest
    ports:
     - 2225:22
    volumes:
     - ${PWD}/data/fs/keeper-02:/var/lib/clickhouse
    networks:
     - bridgenetwork
  keeper-03:
    hostname: keeper-03
    container_name: keeper-03
    image: managed-nodes-base:latest
    ports:
     - 2226:22
    volumes:
     - ${PWD}/data/fs/keeper-03:/var/lib/clickhouse
    networks:
     - bridgenetwork

networks:
  bridgenetwork:
    name: bridgenetwork
